version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=your_db_username
      - DB_PASSWORD=your_db_password
      - DB_NAME=taskmanager
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
